name: Static code analysis
'on':
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Generate code coverage report
        run: |
          cd client
          npm config set legacy-peer-deps true
          npm ci
          cd ../server
          npm i --save @nestjs/passport passport
          npm i --save-dev @types/node
          npm install mongoose
          cd ../client
          npm install -g @angular/cli
          ng test --browsers=ChromeHeadless --watch=false --code-coverage
      - name: Execute SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: ""
