name: Execute frontend and backend unit tests
'on':
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Run Frontend unit tests
        run: |
          cd client
          npm ci
          npm install -g @angular/cli
          ng test --browsers=ChromeHeadless --watch=false
      - name: Run Backend unit tests
        run: |
          cd server
          npm ci
          npm run test
